// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['paper', 'ball', 'frame', 'velocity_button'], function(paper, ball, frame, VelocityButton) {
    var BaseModule;
    return BaseModule = (function() {
      var triggerChange, triggerReset;

      triggerReset = function() {
        return false;
      };

      triggerChange = function() {
        return false;
      };

      BaseModule.prototype.elementSettings = {
        a: {
          color: "red",
          velocity: 10,
          mass: 3,
          radius: 20,
          left: true
        },
        b: {
          color: "blue",
          velocity: 10,
          mass: 5,
          radius: 30,
          left: false
        },
        frame: {
          velocity: 2
        }
      };

      function BaseModule(canvas, options) {
        this.eventDelegator = __bind(this.eventDelegator, this);
        this.canvas = canvas;
        this.paper = new paper.PaperScope();
        this.tool = new this.paper.Tool();
        this.paper.setup(this.canvas);
        this.view = new this.paper.View(canvas);
        this.elements = {
          a: new ball(this.paper, this.elementSettings.a),
          b: new ball(this.paper, this.elementSettings.b),
          frame: new frame(this.paper, this.elementSettings.frame)
        };
        this.paper.view.draw();
        this.eventDelegator();
      }

      BaseModule.prototype.eventDelegator = function() {
        var _this = this;
        this.view.draw = function() {};
        return this.tool.onMouseDown = function() {
          return _this.animate();
        };
      };

      BaseModule.prototype.animate = function() {
        var counter, delta_x, iterations, ld, left, rd, right, run,
          _this = this;
        left = this.elements.a;
        right = this.elements.b;
        counter = 0;
        delta_x = right.position.current.x - left.position.current.x;
        iterations = 0;
        ld = 1;
        rd = -1;
        run = function() {
          if (left.element.position.x > _this.view.size.width) {
            ld *= -1;
          }
          if (left.element.position.x < 0) {
            ld *= -1;
          }
          if (right.element.position.x < 0) {
            rd *= -1;
          }
          if (right.element.position.x > _this.view.size.width) {
            rd *= -1;
          }
          left.element.position.x += ld * left.getVelocity();
          right.element.position.x += rd * right.getVelocity();
          _this.paper.view.draw();
          if (delta_x > 0) {
            return setTimeout(run, 10);
          }
        };
        return run();
      };

      return BaseModule;

    })();
  });

}).call(this);
