// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['paper', 'velocity_button'], function(paper, VelocityButton) {
    var BaseModule;
    return BaseModule = (function() {
      var globalConfig, triggerChange, triggerReset;

      triggerReset = function() {
        return false;
      };

      triggerChange = function() {
        return false;
      };

      globalConfig = {
        a: {
          radius: 10,
          color: "brown",
          mass: 10,
          velocity: 10
        },
        b: {
          radius: 5,
          color: "blue",
          mass: 8,
          velocity: 8
        },
        frame: {
          velocity: 0
        }
      };

      function BaseModule(canvas) {
        this.animation = __bind(this.animation, this);

        this.eventDelegator = __bind(this.eventDelegator, this);

        var _point;
        this.test = " hello world";
        this.canvas = canvas;
        this.paper = new paper.PaperScope();
        this.paper.setup(this.canvas);
        this.tool = new this.paper.Tool();
        _point = new this.paper.Point(10, 10);
        this.elements = {
          a: new this.paper.Path.Circle(_point, 20)
        };
        this.elements.a.fillColor = globalConfig.a.color;
        this.velocityButton = new VelocityButton(this.paper, {
          type: "a"
        });
        this.paper.view.draw();
        this.eventDelegator();
      }

      BaseModule.prototype.eventDelegator = function() {
        return this.tool.onMouseDown = function(event) {
          return alert(this.test);
        };
      };

      BaseModule.prototype.animation = function() {
        var path, size, tL;
        tL = new this.paper.Point(40, 40);
        size = new this.paper.Size(30, 30);
        path = new this.paper.Path.Rectangle(tL, size);
        path.strokeColor = "blue";
        path.fillColor = "blue";
        this.paper.view.onFrame = function(event) {
          return path.rotate(3);
        };
        return this.paper.view.draw();
      };

      return BaseModule;

    })();
  });

}).call(this);
