// Generated by CoffeeScript 1.4.0
(function() {

  define(["base_module", "animation"], function(baseModule, animation) {
    var canvasElements, elementData, modules, parentElements, resize;
    parentElements = {
      "lab": $('#container > div:nth-child(1) > .content'),
      "red": $('#container > div:nth-child(2) > .content'),
      "blue": $('#container > div:nth-child(3) > .content'),
      "custom": $('#container > div:nth-child(4) > .content')
    };
    canvasElements = {
      "lab": parentElements.lab.children("canvas"),
      "red": parentElements.red.children("canvas"),
      "blue": parentElements.blue.children("canvas"),
      "custom": parentElements.custom.children("canvas")
    };
    elementData = {
      lab: {
        a: {
          velocity: 5,
          mass: 3
        },
        b: {
          velocity: -1,
          mass: 5
        },
        frame: {
          velocity: 0
        }
      },
      red: {
        a: {
          mass: 3,
          velocity: 0
        },
        b: {
          mass: 5,
          velocity: -6
        },
        frame: {
          velocity: 0
        }
      },
      blue: {
        a: {
          mass: 3,
          velocity: 6
        },
        b: {
          mass: 5,
          velocity: 0
        },
        frame: {
          velocity: -1
        }
      },
      custom: {
        a: {
          mass: 3,
          velocity: 3
        },
        b: {
          mass: 5,
          velocity: -3
        },
        frame: {
          velocity: 2
        }
      }
    };
    (resize = function() {})();
    return modules = {
      lab: new baseModule(canvasElements.lab[0], elementData.lab),
      red: new baseModule(canvasElements.red[0], elementData.red),
      blue: new baseModule(canvasElements.blue[0], elementData.blue),
      custom: new baseModule(canvasElements.custom[0], elementData.custom)
    };
  });

}).call(this);
