// Generated by CoffeeScript 1.4.0
(function() {

  define(["paper"], function(paper) {
    var Control;
    return Control = (function() {
      var config;

      config = {
        radius: 20,
        playColor: "blue",
        pauseColor: "red",
        backgroundColor: "black",
        verticalOffset: 10
      };

      function Control(paper, callback) {
        this.paper = paper;
        this.callback = callback;
        this.init();
        this.paper.view.draw();
      }

      Control.prototype.init = function() {
        var center;
        center = new this.paper.Point(this.paper.view.size.width * 0.5, this.paper.view.size.height - config.verticalOffset);
        this.circle = new this.paper.Path.Circle(center, 20);
        return this.circle.fillColor = "black";
      };

      Control.prototype.reset = function() {};

      return Control;

    })();
  });

}).call(this);
