// Generated by CoffeeScript 1.4.0
(function() {

  define(["paper"], function(paper) {
    var Frame;
    return Frame = (function() {
      var constructor, init,
        _this = this;

      function Frame() {}

      Frame.prototype.config = {
        editable: false,
        verticalOffset: 20,
        horizontalOffset: 20
      };

      constructor = function(canvas, options) {
        var i, _i, _len;
        this.canvas = canvas;
        this.paper = new paper.PaperScope();
        this.tool = new this.paper.Tool();
        this.view = new this.paper.View(this.canvas);
        for (_i = 0, _len = options.length; _i < _len; _i++) {
          i = options[_i];
          this.config[i] = options[i];
        }
        return this.init();
      };

      init = function() {
        Frame.origin = new Frame.paper.Point(Frame.config.verticalOffset, Frame.config.horizontalOffset);
        Frame.element = new Frame.paper.Circle(Frame.origin, 20);
        return Frame.element.fillColor = "orange";
      };

      return Frame;

    }).call(this);
  });

}).call(this);
