// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(["paper"], function(paper) {
    var Frame;
    return Frame = (function() {

      function Frame(paper, container, options) {
        var key, value;
        this.paper = paper;
        this.container = container;
        this.setVelocity = __bind(this.setVelocity, this);

        this.getVelocity = __bind(this.getVelocity, this);

        this.config = [];
        for (key in options) {
          value = options[key];
          this.config[key] = value;
        }
        this.tag = this.container.find("span:nth-child(2)");
        this.input = this.container.find("input");
      }

      Frame.prototype.getVelocity = function() {
        return this.config.velocity;
      };

      Frame.prototype.setVelocity = function(velocity) {
        this.config.velocity = parseInt(velocity);
        this.tag.html(this.config.velocity);
        return this.input.attr("value", this.config.velocity);
      };

      return Frame;

    })();
  });

}).call(this);
