// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var VelocityButton;
    return VelocityButton = (function() {
      var settings;

      settings = {
        general: {
          bottomOffset: 20,
          rightOffset: 20
        },
        style: {
          strokeColor: "black",
          strokeWidth: 2.5,
          fillColor: "black"
        },
        tip: {
          radius: 8,
          position: 0
        },
        tail: {
          rightOffset: 20,
          width: 4,
          segments: 10,
          minLength: 5,
          maxLength: 20
        }
      };

      function VelocityButton(paper, _settings) {
        this.paper = paper;
        this.tool = new this.paper.Tool();
        this.settings = {
          type: "a",
          height: this.paper.view.size.height,
          width: this.paper.view.size.width,
          tail: {
            length: (settings.tail.minLength + settings.tail.maxLength) * 0.5
          }
        };
        this.shapeInit();
      }

      VelocityButton.prototype.drag = function(event) {
        alert("hello wr");
        return console.log("hello world from range!");
      };

      VelocityButton.prototype.shapeInit = function() {
        var i, _i, _ref, _x, _y;
        this.tail = new this.paper.Path();
        _y = this.settings.height - settings.general.bottomOffset - (settings.tail.width * 1.5);
        for (i = _i = 0, _ref = settings.tail.segments; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _x = this.settings.width - (i * this.settings.tail.length + settings.general.rightOffset);
          this.tail.add(new this.paper.Point(_x, _y));
        }
        this.tail.style = settings.style;
        this.tail.strokeWidth = settings.tail.width;
        _y = this.settings.height - settings.general.bottomOffset - (settings.tip.radius * 0.5);
        _x = this.settings.width - settings.general.rightOffset - (settings.tail.segments * this.settings.tail.length);
        this.tip = new this.paper.Path.RegularPolygon(new this.paper.Point(_x, _y), 3, settings.tip.radius);
        this.tip.style = settings.style;
        return this.tip.rotate((this.settings.type === "a" ? -90 : 90));
      };

      return VelocityButton;

    })();
  });

}).call(this);
